routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');


Route::resource('/alertcontacts', 'AlertContactController');
Route::resource('/alerts', 'AlertController', ['only' => ['index','show']]);
Route::resource('/cameras', 'CameraController');
Route::resource('/solarinstallations', 'SolarInstallationController');
Route::post('/solarinstallations/{id}/secure', 'SolarInstallationController@secure')->name('solarinstallations.secure');
Route::resource('/solarpanels', 'SolarPanelController');
Route::resource('/users', 'UserController');
Route::resource('/videos', 'VideoController');

app/Alert.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Alert extends Model {

    protected $tablename = "alerts";

    protected $guarded = [];

    public function solar_installation()
    {
        return $this->belongsTo('App\SolarInstallation','solar_installation_id');
    }

    public function images()
    {
        return $this->hasMany('App\Image', 'alert_id', 'id');
    }

    public function videos()
    {
        return $this->hasMany('App\Video', 'alert_id', 'id');
    }
}

app/Http/Controllers/AlertController.php
<?php

namespace App\Http\Controllers;

use App\Alert;
use App\AlertContact;
use App\SolarInstallation;
use App\Utilities\SMSSender;
use Illuminate\Http\Request;
use AfricasTalking\SDK\AfricasTalking;

class AlertController extends Controller
{
    // Web
    public function index()
    {
        $data = Alert::all();
        return view('alerts.index', compact("data"));
    }

    public function show($id)
    {
        $data = Alert::findOrFail($id);
        return view('alerts.show', compact("data"));
    }

    // API

    public function store(Request $request)
    {
        $input = $request->validate([
            'solar_installation_id' => 'required|integer|exists:solar_installations,id',
        ]);
        $data = Alert::create($input);
        $contacts = AlertContact::all();
        
        if (isset($data->solar_installation) && $data->solar_installation->alert_contacts->count() > 0) {
            $message = "Breach detected at {$data->solar_installation->name}. View location on map {$data->solar_installation->google_map_url}";
            $receipients = join(',',$data->solar_installation->alert_contacts->pluck('phone_number')->all());
            SMSSender::sendSMS($receipients, $message);
        }

        $installation = SolarInstallation::findOrFail($input['solar_installation_id']);
        $installation->alert_status = true;
        $installation->save();

        return response()->json(['msg' => 'Alert received', 'alert' => $data], 200);
    }

    public function update(Request $request, $id)
    {
        $input = $request->validate([
            'solar_installation_id' => 'required|integer|exists:solar_installations,id',
        ]);
        $data = Alert::find($id)->update($request->all());
        return response()->json(['msg' => 'Alert updated', 'alert' => $data], 200);
    }
}

resources/views/alerts/create.blade.php
@extends('layouts.admin')

@section('admincontent')
    <h1>View Create</h1>
@endsection

resources/views/alerts/edit.blade.php
@extends('layouts.admin')

@section('admincontent')
    <h1>View Edit</h1>
@endsection

resources/views/alerts/index.blade.php
    @extends('layouts.admin')

    @section('admincontent')
        <div class="main-content">
            <div class="section__content section__content--p30">
                <div class="container-fluid">
                    <div class="row m-t-30">
                        <div class="col-md-12">
                            <div class="table-data__tool">
                                <div class="table-data__tool-left">
                                    <h3 class="title-5 m-b-35">Raised alerts</h3>
                                </div>
                            </div>
                            <div class="table-responsive table-responsive-data2">
                                <table class="table table-data2 datatable">
                                    <thead>
                                        <tr>
                                            <th>Date and time</th>
                                            <th>Solar installation</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($data as $alert)
                                            <tr>
                                                <td>{{$alert->created_at}}</td>
                                                <td>
                                                    <a href="{{route('solarinstallations.show',$alert->solar_installation->id)}}">{{$alert->solar_installation->name}}</a>
                                                </td>
                                                <td>
                                                    <a href="{{route('alerts.show', $alert->id)}}" class="item" data-toggle="tooltip" data-placement="top" title="More">
                                                        <i class="zmdi zmdi-more"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endsection

resources/views/alerts/show.blade.php
@extends('layouts.admin')

@section('admincontent')
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                <h2 class="text-center"><a href="{{route('solarinstallations.show',$data->solar_installation->id)}}">{{$data->solar_installation->name}}</a> {{": ".$data->created_at}}</h2>
                <h3 class="m-t-40 text-center">Images</h3>
                <div class="row m-t-30">
                    @foreach ($data->images as $image)
                        <div class="col-sm-4">
                            <div class="image img-fluid">
                                <img class="imagePreview" src="{{asset(Storage::url($image->path))}}" alt="Alert image" />
                            </div>
                        </div>
                    @endforeach
                </div>
                <h3 class="m-t-40 text-center">Videos</h3>
                <div class="row m-t-30">
                    @foreach ($data->videos as $video)
                        <div class="col-lg-6 align-content-center m-0 p-0">
                            <video height="240" controls>
                                <source src="{{Storage::url($video->path)}}" type="video/mp4">
                            </video>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection