routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');


Route::resource('/alertcontacts', 'AlertContactController');
Route::resource('/alerts', 'AlertController', ['only' => ['index','show']]);
Route::resource('/cameras', 'CameraController');
Route::resource('/solarinstallations', 'SolarInstallationController');
Route::post('/solarinstallations/{id}/secure', 'SolarInstallationController@secure')->name('solarinstallations.secure');
Route::resource('/solarpanels', 'SolarPanelController');
Route::resource('/users', 'UserController');
Route::resource('/videos', 'VideoController');

app/Camera.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Camera extends Model {

    protected $tablename = "cameras";

    protected $guarded = [];

    public function solar_installation()
    {
        return $this->belongsTo('App\SolarInstallation','solar_installation_id');
    }
}

app/Http/Controllers/CameraController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Camera;
use App\SolarInstallation;

class CameraController extends Controller
{
    public function index()
    {
        $data = Camera::all();
        return view('cameras.index', compact("data"));
    }

    public function create()
    {
        $solarinstallations = SolarInstallation::all();
        return view('cameras.create', compact("solarinstallations"));
    }

    public function store(Request $request)
    {
        $input = $request->validate([
            'name' => 'required|string|max:50',
            'address' => 'required|url',
            'solar_installation_id' => 'required|integer|exists:solar_installations,id',
        ]);
        $data = Camera::create($input);
        return redirect()->route('solarinstallations.show', $input['solar_installation_id']);
    }

    public function show($id)
    {
        $data = Camera::findOrFail($id);
        return view('cameras.show', compact("data"));
    }

    public function edit($id)
    {
        $solarinstallations = SolarInstallation::all();
        $data = Camera::findOrFail($id);
        return view('cameras.edit', compact("data","solarinstallations"));
    }

    public function update(Request $request, $id)
    {
        $input = $request->validate([
            'name' => 'required|string|max:50',
            'address' => 'required|url',
            'solar_installation_id' => 'required|integer|exists:solar_installations,id',
        ]);
        $data = Camera::findOrFail($id)->update($input);
        return redirect()->route('solarinstallations.show', $input['solar_installation_id']);
    }

    public function destroy($id)
    {
        $row = Camera::findOrFail($id);
        $row->delete();
        $data = Camera::all();
        return redirect()->route('solarinstallations.show', $row->solar_installation_id);
    }
}

resources/views/cameras/create.blade.php
@extends('layouts.admin')

@section('admincontent')
    
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                <div class="flex-wrap">
                    <div class="card">
                        {{-- <div class="card-header">{{ __('Register') }}</div> --}}
                        <div class="card-header">
                            <a href="/">
                                <img src="/images/icon/logo-mini.png" alt="Solar Security">
                            </a>
                        </div>
                        <div class="card-body">
                            <div class="card-title">
                                <h3 class="text-center title-2">Add camera</h3>
                            </div>
                            <form method="POST" action="{{ route('cameras.store') }}" enctype="multipart/form-data">
                                @csrf

                                @forminputfields(['fieldname' => 'name', 'fieldtype' => 'text', 'attributes' => 'required autofocus'])

                                @forminputfields(['fieldname' => 'address', 'fieldtype' => 'text', 'attributes' => 'required'])

                                @forminputfields(['fieldname' => 'solar_installation_id', 'fieldtype' => 'select', 'fieldlabel' => 'Select solar installation', 'fieldoptions' => $solarinstallations->pluck('name','id')])

                                @forminputfields(['fieldtype' => 'submit', 'fieldlabel' => 'Add camera'])
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>

@endsection

resources/views/cameras/edit.blade.php
@extends('layouts.admin')

@section('admincontent')
    
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                <div class="flex-wrap">
                    <div class="card">
                        {{-- <div class="card-header">{{ __('Register') }}</div> --}}
                        <div class="card-header">
                            <a href="/">
                                <img src="/images/icon/logo-mini.png" alt="Solar Security">
                            </a>
                        </div>
                        <div class="card-body">
                            <div class="card-title">
                                <h3 class="text-center title-2">Add camera</h3>
                            </div>
                            <form method="POST" action="{{ route('cameras.update',$data->id) }}" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')

                                @forminputfields(['fieldname' => 'name', 'fieldtype' => 'text', 'attributes' => 'required autofocus', 'fielddefault' => $data->name])

                                @forminputfields(['fieldname' => 'address', 'fieldtype' => 'text', 'attributes' => 'required', 'fielddefault' => $data->address])

                                @forminputfields(['fieldname' => 'solar_installation_id', 'fieldtype' => 'select', 'fieldlabel' => 'Select solar installation', 'fieldoptions' => $solarinstallations->pluck('name','id'), 'fielddefault' => $data->solar_installation_id])

                                @forminputfields(['fieldtype' => 'submit', 'fieldlabel' => 'Add camera'])
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>

@endsection

resources/views/cameras/index.blade.php
    @extends('layouts.admin')

    @section('admincontent')
        <h1>View Index</h1>
    @endsection

resources/views/cameras/show.blade.php
@extends('layouts.admin')

@section('admincontent')
    <h1>View Show</h1>
@endsection