routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');


Route::resource('/alertcontacts', 'AlertContactController');
Route::resource('/alerts', 'AlertController', ['only' => ['index','show']]);
Route::resource('/cameras', 'CameraController');
Route::resource('/solarinstallations', 'SolarInstallationController');
Route::post('/solarinstallations/{id}/secure', 'SolarInstallationController@secure')->name('solarinstallations.secure');
Route::resource('/solarpanels', 'SolarPanelController');
Route::resource('/users', 'UserController');
Route::resource('/videos', 'VideoController');

app/SolarInstallation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SolarInstallation extends Model {

    protected $tablename = "solar_installations";

    protected $guarded = [];

    public function getGoogleMapUrlAttribute()
    {
        return "https://www.google.com/maps/search/?api=1&query={$this->attributes['latitude']},{$this->attributes['longitude']}";
    }

    public function alert_contacts()
    {
        return $this->belongsToMany('App\AlertContact', 'alert_contacts_solar_installations', 'solar_installation_id', 'alert_contact_id');
    }

    public function alerts()
    {
        return $this->hasMany('App\Alert', 'solar_installation_id', 'id');
    }

    public function cameras()
    {
        return $this->hasMany('App\Camera', 'solar_installation_id', 'id');
    }
}

app/Http/Controllers/SolarInstallationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\SolarInstallation;
use Validator;
use App\Http\Requests\CreateSolarInstallation;

class SolarInstallationController extends Controller
{
    public function index()
    {
        $data = SolarInstallation::withCount('alerts')->get();
        return view('solarinstallations.index', compact("data"));
    }

    public function create()
    {
        return view('solarinstallations.create');
    }

    public function store(Request $request)
    {
        $input = $request->validate([
            'name' => 'required|string|max:50|unique:solar_installations,name',
            'location_description' => 'required|string|max:250',
            'latitude' => 'required|string|max:15',
            'longitude' => 'required|string|max:15',
            'picture' => 'required|image',
        ]);
        $storagepath = $request->file('picture')->store('public');
        $input['picture'] = $storagepath;
        $data = SolarInstallation::create($input);
        return view('solarinstallations.show', compact("data"));
    }

    public function show($id)
    {
        $data = SolarInstallation::with(['cameras','alert_contacts','alerts'])->findOrFail($id);
        return view('solarinstallations.show', compact("data"));
    }

    public function edit($id)
    {
        $data = SolarInstallation::findOrFail($id);
        return view('solarinstallations.edit', compact("data"));
    }

    public function update(Request $request, $id)
    {
        $data = SolarInstallation::findOrFail($id);
        $input = $input = $request->validate([
            'name' => 'required|string|max:50|unique:solar_installations,name,'.$data->id,
            'location_description' => 'required|string|max:250',
            'latitude' => 'required|string|max:15',
            'longitude' => 'required|string|max:15',
            'picture' => 'image',
        ]);
        $file = $request->file('picture');
        if (isset($file)) {
            $storagepath = $request->file('picture')->store('public');
            $input['picture'] = $storagepath;
        } else {
            unset($input['picture']);
        }
        $data->update($input);
        return redirect()->route('solarinstallations.show', ['id' => $id]);
    }

    public function destroy($id)
    {
        $row = SolarInstallation::findOrFail($id);
        $row->delete();
        return redirect()->route('solarinstallations.index');
    }

    public function secure(Request $request, $id)
    {
        $data = SolarInstallation::findOrFail($id)->update(['alert_status'=>false]);
        return redirect()->route('solarinstallations.show', ['id' => $id]);
    }
}

resources/views/solarinstallations/create.blade.php
@extends('layouts.admin')

@section('admincontent')
    
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                <div class="flex-wrap">
                    <div class="card">
                        {{-- <div class="card-header">{{ __('Register') }}</div> --}}
                        <div class="card-header">
                            <a href="/">
                                <img src="/images/icon/logo-mini.png" alt="Solar Security">
                            </a>
                        </div>
                        <div class="card-body">
                            <div class="card-title">
                                <h3 class="text-center title-2">Add solar installation</h3>
                            </div>
                            <form method="POST" action="{{ route('solarinstallations.store') }}" enctype="multipart/form-data">
                                @csrf

                                @forminputfields(['fieldname' => 'name', 'fieldtype' => 'text', 'attributes' => 'required autofocus'])

                                @forminputfields(['fieldname' => 'location_description', 'fieldlabel' => 'Location description', 'fieldtype' => 'textarea', 'attributes' => 'cols="30" rows="3"'])

                                @forminputfields(['fieldname' => 'latitude', 'fieldtype' => 'text'])

                                @forminputfields(['fieldname' => 'longitude', 'fieldtype' => 'text'])
                                
                                @forminputfields(['fieldname' => 'picture', 'fieldtype' => 'image'])

                                @forminputfields(['fieldtype' => 'submit', 'fieldlabel' => 'Add solar installation'])
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>

@endsection

resources/views/solarinstallations/edit.blade.php
@extends('layouts.admin')

@section('admincontent')
    
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                <div class="flex-wrap">
                    <div class="card">
                        {{-- <div class="card-header">{{ __('Register') }}</div> --}}
                        <div class="card-header">
                            <a href="/">
                                <img src="/images/icon/logo-mini.png" alt="Solar Security">
                            </a>
                        </div>
                        <div class="card-body">
                            <div class="card-title">
                                <h3 class="text-center title-2">Edit {{$data->name}}</h3>
                            </div>
                            <form method="POST" action="{{ route('solarinstallations.update',$data->id) }}" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')

                                @forminputfields(['fieldname' => 'name', 'fieldtype' => 'text', 'attributes' => 'required autofocus', 'fielddefault' => $data->name])

                                @forminputfields(['fieldname' => 'location_description', 'fieldlabel' => 'Location description', 'fieldtype' => 'textarea', 'attributes' => 'cols="30" rows="3"', 'fielddefault' => $data->location_description])

                                @forminputfields(['fieldname' => 'latitude', 'fieldtype' => 'text', 'fielddefault' => $data->latitude])

                                @forminputfields(['fieldname' => 'longitude', 'fieldtype' => 'text', 'fielddefault' => $data->longitude])
                                
                                @forminputfields(['fieldname' => 'picture', 'fieldtype' => 'image'])

                                @forminputfields(['fieldtype' => 'submit', 'fieldlabel' => 'Update solar installation'])
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/solarinstallations/index.blade.php
    @extends('layouts.admin')

    @section('admincontent')
        <div class="main-content">
            <div class="section__content section__content--p30">
                <div class="container-fluid">
                    <div class="row m-t-30">
                        <div class="col-md-12">
                            <!-- DATA TABLE-->
                            <div class="table-data__tool">
                                <div class="table-data__tool-left">
                                    <h3 class="title-5 m-b-35">Solar Installations</h3>
                                </div>
                                <div class="table-data__tool-right">
                                    <a href="{{route('solarinstallations.create')}}" class="btn au-btn au-btn-icon au-btn--green au-btn--small">
                                        <i class="zmdi zmdi-plus"></i>Add Item
                                    </a>
                                </div>
                            </div>
                            <div class="table-responsive m-b-40">
                                <table class="table table-borderless table-data2 datatable">
                                    <thead>
                                        <tr>
                                            <th>Status</th>
                                            <th>Name</th>
                                            <th>Location</th>
                                            <th>Alerts raised</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($data as $solarinstallation)
                                            <tr>
                                                @if ($solarinstallation->alert_status)
                                                    <td class="text-danger">Alarm raised</td>
                                                @else
                                                    <td class="text-success">Secure</td>
                                                @endif
                                                <td>{{$solarinstallation->name}}</td>
                                                <td>
                                                    <a href="{{$solarinstallation->google_map_url}}" target="_blank">{{$solarinstallation->location_description}}</a>
                                                </td>
                                                <td>
                                                    {{$solarinstallation->alerts_count}}
                                                </td>
                                                <td>
                                                    <div class="table-data-feature">
                                                        <a href="{{route('solarinstallations.edit', $solarinstallation->id)}}" class="item" data-toggle="tooltip" data-placement="top" title="Edit">
                                                            <i class="zmdi zmdi-edit"></i>
                                                        </a>
                                                        <form action="{{route('solarinstallations.destroy', $solarinstallation->id)}}" method="POST">
                                                            @csrf
                                                            @method('DELETE')
                                                            <button type="submit" class="item" data-toggle="tooltip" data-placement="top" title="Delete">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </form>
                                                        <a href="{{route('solarinstallations.show', $solarinstallation->id)}}" class="item" data-toggle="tooltip" data-placement="top" title="More">
                                                            <i class="zmdi zmdi-more"></i>
                                                        </a>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <!-- END DATA TABLE-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endsection

resources/views/solarinstallations/show.blade.php
@extends('layouts.admin')

@section('admincontent')
    <div class="main-content">
        <div class="section__content section__content--p30">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-5">
                        <div class="flex-wrap h-100">
                            <div class="card h-100">
                                <img class="card-img-top" src="{{Storage::url($data->picture)}}" alt="Solar installation {{$data->name}}">
                                <div class="card-body">
                                    <h6 class="card-title mb-3 title-2">
                                        {{$data->name}}
                                        @if ($data->alert_status)
                                            <span class="badge badge-danger pull-right" style="font-size: 13px;">
                                                <i class="zmdi zmdi-alert-octagon"></i>
                                                ALARM RAISED
                                            </span>
                                        @else
                                            <span class="badge badge-success pull-right" style="font-size: 13px;">
                                                <i class="zmdi zmdi-lock"></i>
                                                SECURE
                                            </span>
                                        @endif
                                    </h6>
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <a class="btn btn-block btn-info" href="{{route('solarinstallations.edit',$data->id)}}">Edit</a>
                                        </div>
                                        <div class="col-sm-6">
                                            @if ($data->alert_status)
                                                <form action="{{route('solarinstallations.secure', $data->id)}}" method="post">
                                                    @csrf
                                                    <button type="submit" class="btn btn-block btn-danger">SECURE</button>
                                                </form>
                                            @else
                                                <button class="btn btn-block btn-danger" disabled="disabled">ALARM OFF</button>
                                            @endif
                                        </div>
                                    </div>
                                    <p class="card-text m-t-20">
                                        {{$data->location_description}}
                                    </p>
                                </div>
                                <div class="card-footer">
                                    <a href="{{$data->google_map_url}}" class="btn btn-block btn-light" target="_blank">
                                        <i class="zmdi zmdi-google-maps"></i>&nbsp; View on google map
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-7">
                        <div class="top-campaign">
                            <div class="table-data__tool">
                                <div class="table-data__tool-left">
                                    <h3 class="title-3 m-b-30">Alert contacts</h3>
                                </div>
                                <div class="table-data__tool-right">
                                    <a href="{{route('alertcontacts.index')}}" class="au-btn au-btn-icon au-btn--green au-btn--small">
                                        <i class="zmdi zmdi-plus"></i>add alert contact
                                    </a>
                                </div>
                            </div>
                            <div class="table-responsive">
                                <table class="table table-top-campaign">
                                    <tbody>
                                        @foreach ($data->alert_contacts as $alert_contact)
                                            <tr>
                                                <td>{{$alert_contact->name}}</td>
                                                <td>{{$alert_contact->email}}</td>
                                                <td>{{$alert_contact->phone_number}}</td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div>
                            <div class="table-data__tool">
                                <div class="table-data__tool-left">
                                    <h3 class="title-5 m-b-35">Cameras</h3>
                                </div>
                                <div class="table-data__tool-right">
                                    <a href="{{route('cameras.create')}}" class="au-btn au-btn-icon au-btn--blue2 au-btn--small">
                                        <i class="zmdi zmdi-plus"></i>add camera
                                    </a>
                                </div>
                            </div>
                            <div class="table-responsive table-responsive-data2">
                                <table class="table table-data2">
                                    <thead>
                                        <tr>
                                            <th>Camera link</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($data->cameras as $camera)
                                            <tr>
                                                <td><a href="{{$camera->address}}">{{$camera->name}}</a></td>
                                                <td>
                                                    <div class="table-data-feature">
                                                        <a href="{{route('cameras.edit', $camera->id)}}" class="item" data-toggle="tooltip" data-placement="top" title="Edit">
                                                            <i class="zmdi zmdi-edit"></i>
                                                        </a>
                                                        <form action="{{route('cameras.destroy', $camera->id)}}" method="POST">
                                                            @csrf
                                                            @method('DELETE')
                                                            <button type="submit" class="item" data-toggle="tooltip" data-placement="top" title="Delete">
                                                                <i class="zmdi zmdi-delete"></i>
                                                            </button>
                                                        </form>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="container">
                            <h3 class="title-5 m-b-35">Raised alerts</h3>
                            <div class="table-responsive table-responsive-data2">
                                <table class="table table-data3 datatable">
                                    <thead>
                                        <tr>
                                            <th>Date and time</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($data->alerts as $alert)
                                            <tr>
                                                <td>
                                                    <a href="{{route('alerts.show',$alert->id)}}" data-toggle="tooltip" data-placement="top" title="View details">
                                                        {{$alert->created_at}}
                                                    </a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection