routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard.index');


Route::resource('/alertcontacts', 'AlertContactController');
Route::resource('/alerts', 'AlertController', ['only' => ['index','show']]);
Route::resource('/cameras', 'CameraController');
Route::resource('/solarinstallations', 'SolarInstallationController');
Route::post('/solarinstallations/{id}/secure', 'SolarInstallationController@secure')->name('solarinstallations.secure');
Route::resource('/solarpanels', 'SolarPanelController');
Route::resource('/users', 'UserController');
Route::resource('/videos', 'VideoController');

resources/views/includes/adminsidebar.blade.php
<ul class="list-unstyled navbar__list">
    <li>
        <a href="{{route('dashboard.index')}}"><i class="fas fa-tachometer-alt"></i>Dashboard</a>
    </li>
    <li>
        <a href="{{route('alerts.index')}}"><i class="fas fa-warning"></i>Alerts</a>
    </li>
    <li>
        <a href="{{route('solarinstallations.index')}}"><i class="fas fa-sun"></i>Solar Installations</a>
    </li>
    <li>
        <a href="{{route('alertcontacts.index')}}"><i class="fas fa-user"></i>Alert contacts</a>
    </li>
</ul>

resources/views/includes/forminputfields.blade.php
@if ($fieldtype == 'submit')
    <div class="form-group row mb-0">
        <div class="col-md-8 offset-md-2">
            <button type="submit" class="btn btn-primary btn-block">
                    {{ __(isset($fieldlabel) ? $fieldlabel : 'Submit') }}
            </button>
        </div>
    </div>
@else
    <div class="form-group row">
        <label for="{{isset($fieldid) ? $fieldid : $fieldname}}" class="col-md-4 col-form-label text-md-right">{{ __(isset($fieldlabel) ? $fieldlabel : ucfirst($fieldname)) }}</label>

        <div class="col-md-6">
            @if($fieldtype == 'image')
                <div class="col-sm-12 imgUp">
                    <div class="imagePreview"></div>
                    <label class="btn btn-dark">
                        Choose file to upload
                        <input type="file" class="uploadFile img{{ $errors->has($fieldname) ? ' is-invalid' : '' }}" value="Upload Image" style="width: 0px;height: 0px;overflow: hidden;" id="{{isset($fieldid) ? $fieldid : $fieldname}}" name="{{$fieldname}}" {{isset($attributes) ? $attributes : ''}}>
                    </label>
                </div>
            @elseif($fieldtype == 'radio')
                <label class="switch switch-3d switch-primary mr-3">
                    <input id="{{isset($fieldid) ? $fieldid : $fieldname}}" type="radio" class="switch-input form-control{{ $errors->has($fieldname) ? ' is-invalid' : '' }}" {{(isset($fielddefault) && $fielddefault) ? 'checked' : ''}} name="{{$fieldname}}"  value="{{$fieldvalue}}" {{isset($attributes) ? $attributes : ''}}>
                    <span class="switch-label"></span>
                    <span class="switch-handle"></span>
                </label>
            @elseif($fieldtype == 'checkbox')
                <label class="switch switch-3d switch-primary mr-3">
                    <input id="{{isset($fieldid) ? $fieldid : $fieldname}}" type="checkbox" class="switch-input form-control{{ $errors->has($fieldname) ? ' is-invalid' : '' }}" {{(isset($fielddefault) && $fielddefault) ? 'checked' : ''}} name="{{$fieldname}}" value="{{$fieldvalue}}" {{isset($attributes) ? $attributes : ''}}>
                    <span class="switch-label"></span>
                    <span class="switch-handle"></span>
                </label>
            @elseif($fieldtype == 'select')
                <select id="{{isset($fieldid) ? $fieldid : $fieldname}}" class="form-control{{ $errors->has($fieldname) ? ' is-invalid' : '' }}" name="{{$fieldname}}" {{isset($attributes) ? $attributes : ''}}>
                        <option value="-1">{{ __(isset($fieldlabel) ? $fieldlabel : ucfirst($fieldname)) }}</option>    
                    @foreach ($fieldoptions as $optionvalue => $optionlabel)
                        <option value="{{$optionvalue}}" {{ (isset($fielddefault) && $fielddefault == $optionvalue) ? 'selected' : '' }}>{{$optionlabel}}</option>
                    @endforeach
                </select>
            @elseif($fieldtype == 'textarea')
                <textarea id="{{isset($fieldid) ? $fieldid : $fieldname}}" type="{{$fieldtype}}" class="au-input au-input--full form-control{{ $errors->has($fieldname) ? ' is-invalid' : '' }}" name="{{$fieldname}}" {{isset($attributes) ? $attributes : ''}}>{{ isset($fielddefault) ? $fielddefault : old($fieldname) }}</textarea>
            @else
                <input id="{{isset($fieldid) ? $fieldid : $fieldname}}" type="{{$fieldtype}}" class="au-input au-input--full form-control{{ $errors->has($fieldname) ? ' is-invalid' : '' }}" name="{{$fieldname}}" value="{{ isset($fielddefault) ? $fielddefault : old($fieldname) }}" {{isset($attributes) ? $attributes : ''}}>
            @endif

            @if ($errors->has($fieldname))
                <span class="text-danger error">
                    <strong>{{ $errors->first($fieldname) }}</strong>
                </span>
            @endif
        </div>
    </div>    
@endif

resources/views/includes/logout.blade.php
<a href="{{ route('logout') }}"
    onclick="event.preventDefault();
                    document.getElementById('__user-logout-form').submit();">
    <i class="zmdi zmdi-power-off"></i>
    {{ __('Logout') }}
</a>

<form id="__user-logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
    @csrf
</form>